### PR TITLE
Upgrading to scala 2.11

### PR DESCRIPTION
**Pull request by vineethvarghese**

### CODE REVIEW

**Comment by stephanh** [comment]
Do you want to bump the sbt version as well?

**Comment by stephanh** [comment]
:+1:

**Comment by vineethvarghese** [comment]
will do

**Comment by vineethvarghese** [comment]
do you mean 0.13.8?

**Comment by stephanh** [comment]
Yeah

**Comment by vineethvarghese** [comment]
ok

**Pull request merged**
